[package]
name = "game_of_life"
version = "0.1.0"
authors = ["Nir Geller <gnir.work@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
log = "0.4.14"
env_logger = "0.8.3"
termion = "1.5.6"